name: dev_server
description: A development server for Angular app
version: 0.0.1
#homepage: https://www.example.com
author: Kevin Segaud <segaud.kevin@gmail.com>

executables:
  dev_server: main

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  shelf: ^0.7.3+3
  mime: ^0.9.6+2
  logging: ^0.11.3+2
  
dev_dependencies:
  test: ^1.3.0
